cmd/cli/cmds/rum.go, lib/cli/print.go, pkg/csv.go, pkg/table.go
This adds CSV/TSV export. It also adds a flag to skip headers.
This closes #1 and #2.
- :sparkles: Add CSV export to TableOutputFormatter
- :tractor: Reorganize structure
- :sparkles: Add CSV and TSV support
- :sparkles: Add command line flags to tweak CSV output
=> Add CSV export

README.md, cmd/glaze/main.go, pkg/cli/cobra.go, pkg/cli/settings.go, pkg/formatters/json.go, pkg/formatters/yaml.go
- :sparkles: Add support for yaml output
- :ambulance: Add support for flattened objects for yaml output
=> Add YAML output formatter to lib and glaze

cmd/glaze/doc/examples/templates-example-3.md, pkg/cli/helpers.go, pkg/help/templates/help-short-section-list.tmpl
The most important change here is adding a `OutputFormatter()` accessor method to `GlazeProcessor`
- :art: Add some more helpers for sqleton
- :art: Don't show full example content in short lists
- :memo:  Prettify documentation a bit
=> Small tweaks to support sqleton

cmd/glaze/doc/topics/templates.md, misc/template-file-example.tmpl.md, misc/template-file-example2.tmpl.md, misc/test-data/book.json, pkg/cli/cobra.go, pkg/cli/helpers.go, pkg/cli/settings.go, pkg/formatters/template.go, pkg/helpers/files.go, pkg/helpers/templating.go
This adds support for rendering a table using a template file.
Additional data can be passed through a --template-data argument.
Closes #88
- :sparkles: Add tempalting output
- :sparkles: Add --template-data functionality
=> Add support for templated output

cmd/glaze/doc/topics/templates.md, misc/replace.yaml, misc/test-data/books.json, pkg/cli/cobra.go, pkg/cli/settings.go, pkg/helpers/templating.go, pkg/middlewares/replace.go, pkg/middlewares/replace_test.go
This is the first pass at adding replace and skip functionality, as I need 
it for work.
This is not perfect, and there is no documentation yet, as I want to make it possible
to specify skips and replacements on the command line too. It currently only works
using a yaml file to configure it all at once.
- :art: Add a few more templating functions that were left over from some other hacking:
- :sparkles: Load replacement middleware from YAML
- :sparkles: Add proper flags for running replacements
=> Add replace and skip functionality

pkg/cmds/cmds.go, pkg/cmds/cobra.go, pkg/helpers/templating.go
It was not possible to register commands with more than one directory depth
because of a bug in the findParent loop.
Closes #105
- :ambulance: Properly handle parent commands when loading from FS
- :art: Add quoteNewlines templating function
=> :ambulance: Fix command parents not being set properly

cmd/glaze/cmds/json.go, cmd/glaze/cmds/markdown.go, cmd/glaze/main.go, go.mod, go.sum
This is a rough take on adding support for markdown parsing, mostly
because I wanted support for splitting markdown files by header.
This is a start to work on #112 but is definitely not where it should stop.
- :sparkles: Add sketch for markdown parsing verb
- :sparkles: Add actually useful split-by-heading command
=> Add starting command to process markdown

pkg/helpers/concurrency.go
This adds a few concurrency tools useful for CLI applications.
One of them is to cancel a context on CTRL-C (or other signals).
One is to merge multiple channels into a single one.
=> Add simple concurrency tools

.goreleaser.yaml, cmd/glaze/main.go, pkg/cmds/alias.go, pkg/cmds/cmds.go, pkg/cmds/cobra.go, pkg/cmds/doc.go, pkg/help/help.go
We used to have an embedFS and a separate Dir implementation,
mostly out of ignorance. 
They are now unified for both HelpSections and Commands loading.
Breaks existing APIs.
```
_______  _______    _______  _______    _______  _______ 
|       ||       |  |       ||       |  |       ||       |
|    ___||   _   |  |    ___||   _   |  |    ___||   _   |
|   | __ |  | |  |  |   | __ |  | |  |  |   | __ |  | |  |
|   ||  ||  |_|  |  |   ||  ||  |_|  |  |   ||  ||  |_|  |
|   |_| ||       |  |   |_| ||       |  |   |_| ||       |
|_______||_______|  |_______||_______|  |_______||_______|
_______  _______  __   __  __   __  _______  __    _  ______   _______ 
|       ||       ||  |_|  ||  |_|  ||   _   ||  |  | ||      | |       |
|       ||   _   ||       ||       ||  |_|  ||   |_| ||  _ …
```
=> Refactor embed/dir FS handling to be a single function

pkg/cli/cobra.go, pkg/cmds/alias.go, pkg/cmds/cmds.go
The refactor moving commands and aliases into glazed broke aliases for two reasons:
- the yaml parse error that was the signal for parsing a yaml file as an alias was broken because of wrapping the parse error
- glazed flags that were previously set for every alias in sqleton were now missing the glazed flatgs
The glazed helper flags are now set as PersistentFlags(), but considering the refactor of the entire
declarative flags sections, it will make more sense to add the glazed flags to the declarative flags
of the commands themselves, and thus register them properly. 
This might happen in a second step of the declarative flag refactor, however.
See also: https://github.com/go-go-golems/glazed/issues/136
- :art: Fix broken aliases
- :art: Register glazed commands as persistentflags so …
=> :ambulance: Fix aliases

pkg/cmds/layers/cobra_flag_groups.go, pkg/cmds/parameters/parameters.go
Closes #174
- :sparkles: Allow parsing *FromFile functions without files
=> Allow parsing *FromFile without file

cmd/glaze/cmds/docs.go, pkg/cli/glazed_layer.go, pkg/cli/settings_fields-filters.go, pkg/cli/settings_output.go, pkg/cli/settings_rename.go, pkg/cli/settings_replace.go, pkg/cli/settings_select.go, pkg/cli/settings_template.go, pkg/cmds/layers/groups.go
Closes #183
This makes things a little bit nicer wrt configuring individual glazed layers, instead
of having to call InitializeParameterDefaultsFromStruct by hand.
=> :sparkles: Move to an options based way of configuring glaze parameter layer

go.mod, go.sum, pkg/cli/flags/fields-filters.yaml, pkg/cmds/cmds.go, pkg/formatters/csv.go, pkg/formatters/json.go, pkg/formatters/table.go, pkg/formatters/template.go, pkg/formatters/yaml.go, pkg/help/cobra.go, pkg/help/templates/cobra-usage.tmpl, pkg/helpers/templating.go
- :art: Add GetTable() API to OutputFormatter
- :ambulance: Use bmatcuk/doublestar and not filepathx
- :ambulance: Don't try to pass options to aliases
- :art: :lipstick: Prettify output of help commands list
- :tractor: :sparkles: Properly handle commands parents when loading from YAML
=> Add GetTable to OutputFormatter, make help usage prettier, fix Parents setting

Makefile, pkg/cmds/cmds.go
- :art: Try using svu
- :art: Push --tags instead of more restricted push
- :ambulance: Properly handle source/parents of yaml commands
=> Properly handle prefix of embedded yaml commands

go.mod, go.sum, pkg/cli/flags/fields-filters.yaml, pkg/cli/flags/jq.yaml, pkg/cli/flags/output.yaml, pkg/cli/flags/rename.yaml, pkg/cli/flags/replace.yaml, pkg/cli/flags/select.yaml, pkg/cli/flags/template.yaml, pkg/cli/glazed_layer.go, pkg/cli/settings_jq.go, pkg/middlewares/jq.go, pkg/middlewares/jq_test.go, pkg/middlewares/mod.go
This adds very simple jq support, both at the object level and at the table 
level. 
The biggest limitation is that it is currently not possible to return multiple objects from an 
object level middleware, but only a single row. This should however be fixed soon.
The semantics of returning multiple values from a field based jq expression are less clear.
Closes #85 
- :sparkles: Add jq middlware
- :sparkles: Properly parse and add jq to the CLI tool
- :ambulance: Fix --field-jq as well
=> Add simple jq support

cmd/glaze/cmds/docs.go, pkg/cli/cobra.go, pkg/cmds/alias.go, pkg/cmds/cmds.go, pkg/help/cobra.go
This splits the Command interface into two interfaces:
- Command handles only the Description() part and allows us to wrap commands into CLI apps
- GlazeCommand is focused on the Run() method and running things into a GlazeProcessor
- :art: Split Command into GlazeCommand and Command
- :sparkles: Make loaders only deal with Command, GlazeCommand can come later
=> Split Command into GlazeCommand and Command

pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parse.go, pkg/cmds/parameters/parse_test.go, pkg/helpers/cast/cast.go
Closes #233
- :tractor: Split out parsing into its own separate files for better unit test visibility
- :sparkles: :umbrella: Add tons of unit tests
- :sparkles: Add TSV/CSV parsing for object from file
- :sparkles: Add CSV to ObjectListFromFile
- :sparkles: Add CSV support to keyvalue
=> Add CSV support to objectFromFile,objectListFromFile,keyValue,stringListFromFile

pkg/cli/settings_output.go, pkg/cmds/cmds.go, pkg/cmds/processor.go, pkg/formatters/csv.go, pkg/formatters/csv_test.go, pkg/formatters/json.go, pkg/formatters/json_test.go, pkg/formatters/table.go, pkg/formatters/table_test.go, pkg/formatters/template.go, pkg/formatters/template_test.go, pkg/formatters/yaml.go, pkg/formatters/yaml_test.go
Closes #248
- :ambulance: Make output-file work with CSV
- :ambulance: Add OutputFile to templateoutput formatter
- :ambulance: Add OutputFile to templateoutput formatter
- :ambulance: Add output-file to yaml
- :ambulance: Add output-file to json
=> :ambulance: Make output-file work with all formatters

cmd/glaze/cmds/html/parse_test.go, cmd/glaze/doc/examples/output/multiple-output-file.md, cmd/glaze/doc/topics/03-templates.md, pkg/cli/cobra.go, pkg/cli/flags/output.yaml, pkg/cli/glazed_layer.go, pkg/cli/settings_fields-filters.go, pkg/cli/settings_output.go, pkg/cli/settings_rename.go, pkg/cli/settings_replace.go, pkg/cli/settings_select.go, pkg/cli/settings_sort.go, pkg/cli/settings_template.go, pkg/cmds/processor.go, pkg/formatters/csv/csv.go, pkg/formatters/csv/csv_test.go, pkg/formatters/excel/excel.go, pkg/formatters/formatter.go, pkg/formatters/json/json.go, pkg/formatters/json/json_test.go, pkg/formatters/simple/simple.go, pkg/formatters/table/table.go, pkg/formatters/table/table_test.go, pkg/formatters/template/template.go, pkg/formatters/template/template_test.go, pkg/formatters/yaml/yaml.go, pkg/formatters/yaml/yaml_test.go
- :fire: Remove deprecated code
- :tractor: Move formatters to their own packages
- :art: Add option builder for all output formatters
- :art: Rename OutputFormatter classes
- :art: Pass in options to output multiple files (but don't handle yet)
- :sparkles: Implement multi-output-files for CSV
- :sparkles: Add documentation for output-file-template
- :sparkles: Add multiple output files to json
- :sparkles: Add multi file output to table output
- :sparkles: Add multi-output-file support to template
- :sparkles: Add multi output files support to yaml
=> Add multiple output files

cmd/glaze/cmds/yaml.go, pkg/cli/settings_output.go, pkg/cmds/parameters/cobra.go, pkg/formatters/yaml/yaml.go
- :art: Allow for empty yaml files
- :sparkles: Add output-as-objects to yaml
- :ambulance: Don't revert to default value if an empty string is passed for stringList
=> Add yaml output-as-objects, fix smaller issues

Makefile, cmd/glaze/cmds/csv.go, cmd/glaze/cmds/docs.go, cmd/glaze/cmds/html/cmds.go, cmd/glaze/cmds/html/parse.go, cmd/glaze/cmds/html/parse_test.go, cmd/glaze/cmds/json.go, cmd/glaze/cmds/markdown.go, cmd/glaze/cmds/yaml.go, go.mod, go.sum, pkg/cli/cobra.go, pkg/cli/glazed_layer.go, pkg/cmds/alias/alias.go, pkg/cmds/cmds.go, pkg/formatters/csv/csv.go, pkg/formatters/csv/csv_test.go, pkg/formatters/excel/excel.go, pkg/formatters/formatter.go, pkg/formatters/json/json.go, pkg/formatters/json/json_test.go, pkg/formatters/simple/simple.go, pkg/formatters/table/table.go, pkg/formatters/table/table_test.go, pkg/formatters/template/template.go, pkg/formatters/template/template_test.go, pkg/formatters/yaml/yaml.go, pkg/formatters/yaml/yaml_test.go, pkg/processor/processor.go, pkg/processor/processor_test.go
- :tractor: Move processor to its own package
- :art: Break API and add Context parameter to Output()
- :art: Bump go.mod
- :fire: :sparkles: Add writer to all output formatters
=> Refactor OutputFormatter API to have context and writer

pkg/cmds/layers/groups.go, pkg/formatters/formatter.go, pkg/helpers/templating/templating.go, pkg/processor/processor.go, pkg/settings/glazed_layer.go
- :ambulance: Join baseDir to strip from template name when loading things from ParseHTMLFS
- :art: Add MergeParameters helper method
- :art: Use processor options for configuring processors
- :ambulance: Fix rendering of datatables template
=> :art: Add new processor options and don't template streams to string for HTML

cmd/glaze/cmds/html/parse_test.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parameters_test.go, pkg/formatters/csv/csv.go, pkg/formatters/excel/excel.go, pkg/formatters/formatter.go, pkg/formatters/json/json.go, pkg/formatters/simple/simple.go, pkg/formatters/table/table.go, pkg/formatters/template/template.go, pkg/formatters/yaml/yaml.go, pkg/helpers/strings/strings.go, pkg/settings/settings_rename.go
Related to https://github.com/go-go-golems/parka/issues/51
- :art: Rename helper functions to load ParameterDefinitions from a YAML list
- :art: Handle nil setting for rename fields
- :art: Add UniqueStrings helper method
- :art: Add ContentType method to OutputFormatter
- :ambulance: Make TestFormatter support ContentType as well
=> :art: Make the API changes necessary to support parka config file options

pkg/formatters/csv/csv.go, pkg/formatters/table/table.go, pkg/settings/flags/output.yaml, pkg/settings/glazed_layer.go, pkg/settings/settings_output.go
- :art: Output markdown and HTML as rows now too
- :sparkles: Restore the table formatters and add an explicit --stream flag
=> :sparkles: Add stream output flag and restore TableFormatters

cmd/glaze/cmds/csv.go, cmd/glaze/cmds/example.go, cmd/glaze/cmds/json.go, cmd/glaze/cmds/yaml.go, cmd/glaze/doc/tutorials/01-a-simple-table-cli.md, pkg/cli/cobra.go, pkg/cmds/alias/alias.go, pkg/cmds/cmds.go, pkg/cmds/layers/groups.go, pkg/cmds/layout/layout.go, pkg/settings/glazed_layer.go, pkg/settings/settings_fields-filters.go, pkg/settings/settings_jq.go, pkg/settings/settings_output.go, pkg/settings/settings_rename.go, pkg/settings/settings_replace.go, pkg/settings/settings_select.go, pkg/settings/settings_sort.go, pkg/settings/settings_template.go, pkg/types/mod.go
This adds the first building blocks to allow for commands to introspect
their flags and arguments but also provide a generic interface to provide 
access to their declarative content (if possible). It currently only handles
serializing to YAML in a single file, but this will be extended for the richer possibilities
of bundled commands like in escuse-me.
The main change here is that Command now requires the implementation of a `ToYAML()` method, 
which is provided per default for `CommandDescription` itself. However, to make the job easier,
most commands that currently had an explicit `*CommandDescription` field now embed it, so that they can reuse the default `Description()` and `ToYAML()` methods. This change has been reverberating through all the other GO GO GOLEMS modules because it …
=> :sparkles: Add YAML introspection

pkg/cli/cobra.go, pkg/cmds/parameters/parameters.go, pkg/helpers/reflect/reflect.go, pkg/helpers/reflect/reflect_test.go
- :sparkles: Add support to set uint from string (used when loading from ENV)
- :art: Check for nil value when initializing structs
- :ambulance: Instantiate aliases for writer commands too
=> :art: :ambulance: Small fixes

pkg/cli/cobra.go, pkg/cmds/parameters/parameters.go, pkg/helpers/list/list.go, pkg/helpers/templating/templating.go
Related to https://github.com/go-go-golems/parka/issues/84
- :sparkles: Add StructToMap as a preparatory step for codegen of commands
- :sparkles: Add helper function to render values to valid HTTP query parameters
=> :sparkles: Add small helper functions

pkg/cmds/cobra.go, pkg/cmds/parameters/cobra.go, pkg/cmds/parameters/cobra_test.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parameters_test.go, pkg/cmds/parameters/parse.go, pkg/cmds/parameters/parse_test.go, pkg/cmds/parameters/render.go, pkg/cmds/parameters/test-data/parameters_test.yaml, pkg/cmds/parameters/test-data/parameters_validity_test.yaml, pkg/helpers/cast/cast.go, pkg/helpers/reflect/reflect.go
feat: Add choice list parameter type
This adds support for a new choiceList parameter type to allow multiple selections from a set of choices. 
To implement this in a clean way, the logic for parameter default value handling was refactored:
- Split out InitializeValueToEmptyValue to set empty value based on type 
- Created SetValueFromInterface to assign any value to reflect.Value
- Updated SetValueFromDefault to initialize value from default
Additional changes:
- Expanded parameter value validation tests
- Refactored parsing tests to use table-driven pattern
- Added overview documentation for ParameterDefinition
This provides a more flexible way to handle parameter default values while supporting the new choiceList type. Users can now select multiple options from a predefined choice …
=> Add choiceList type

pkg/cli/cobra.go, pkg/cmds/cobra_test.go, pkg/cmds/parameters/cobra-gather-arguments_test.go, pkg/cmds/parameters/cobra-parse-arguments_test.go, pkg/cmds/parameters/cobra.go, pkg/cmds/parameters/cobra_test.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parameters_test.go, pkg/cmds/parameters/test-data/types.yaml, pkg/doc/topics/06-usage-string.md, scripts/param-definitions.sh
Add argument info to cobra command Use field 
This PR updates the cobra integration to populate the Use field with a generated string that incorporates the argument definitions. 
The Use string now shows:
- Required vs optional arguments
- Default values 
- List arguments that accept multiple values
Some key points:
- A new function GenerateUseString was added to create the Use string.
- Required args are in <>, optional in [], lists end in ..., defaults show the value.
- The ordering of arguments is maintained from the definition list.
On the implementation side:
- Argument parsing logic was moved to its own function GatherArguments for easier testing.
- Switched to using an OrderedMap instead of a regular map to preserve order.
- Added more parameter type tests for list and file-loading …
=> :sparkles: Properly show arguments in use string 

README.md, pkg/cli/cobra.go, pkg/cmds/cmds.go, pkg/cmds/layers/groups.go, pkg/cmds/loaders/loaders.go, pkg/helpers/cast/cast.go, prompto/glazed/definitions, scripts/param-definitions.sh
- :sparkles: Add function to cast typed lists to []interface{}
- :art: Rename promptgen to prompto
- :fire: Remove over-engineered LayerParameterParserFunc
=> :fire: Remove over-engineered LayerParameterParserFunc

.goreleaser.yaml, pinocchio/glazed/create-help.yaml, pkg/cmds/parameters/cobra.go, pkg/cmds/parameters/strings.go, pkg/cmds/parameters/strings_test.go, pkg/doc/topics/09-gather-flags-from-string-list.md
This PR adds a new `GatherFlagsFromStringList` function to parse command line flags from a string slice without requiring cobra bindings.
Having a utility function to parse flags from strings makes it easy to handle command line arguments programmatically without coupling to a specific command line library like cobra. This function can be useful in testing and also enables parsing flags from arbitrary string slices.
- Add `GatherFlagsFromStringList` function
- Accepts args []string, params []*ParameterDefinition
- Returns map[string]interface{} of parsed flags
- Handles boolean, string, int, float, and list variant of each
- Can ignore required or only include provided flags
- Gathers remaining args not parsed as flags
- Add tests cases for various argument combinations
- Add new topic to …
=> Add flags/arguments parsing from string list

pinocchio/glazed/create-template-command.yaml, pkg/cmds/parameters/cobra.go, pkg/cmds/template.go, pkg/doc/topics/10-template-command.md
This PR adds a new `TemplateCommand` type that makes it easy to define a command that renders template text. 
The template text is defined in the `template` field of the YAML file, and flags/params are used to render the template content when called.
We often need to quickly render some modular templated text (for example, for prompto documentation contexts). This can now be done with a simple YAML file that can be picked up (again, by prompto for example).
- Add `TemplateCommand` as a WriterCommand
- Add loader to handle `TemplateCommand` YAML
- Update docs
```yaml
name: greeting 
short: Renders a greeting template
flags:
- name: name
type: string
help: Name to greet
- name: hobbies 
type: stringList
help: Hobbies
template: |
Hello {{.name}}!
Your hobbies are:
{{ range .hobbies }}
- {{ . …
```
=> :sparkles: Add template command

pkg/cli/cobra.go
This pull request introduces a 'glazed command layer' to improve the organization of command flags by separating general command options from app-specific flags. 
Key Changes:
- Creation of a new 'glazed-command' parameter layer. This layer includes the following flags:
- "create-command"
- "create-alias"
- "create-cliopatra"
- "print-yaml"
- "load-parameters-from-json"
- These flags were previously defined directly in the `BuildCobraCommandFromCommandAndFunc` function. They have now been moved to the 'glazed-command' layer.
=> :sparkles: Add glazed command layer

pkg/cli/cobra.go, pkg/cmds/cmds.go, pkg/middlewares/processor.go
- Introduced `CommandWithMetadata` interface in `pkg/cmds/cmds.go`, extending `Command` interface with a `Metadata` method.
- Resolved bug in `pkg/cli/cobra.go` causing `glazedCommandLayer` to be added twice to `description.Layers`.
- Added assertion in `pkg/middlewares/processor.go` to confirm `TableProcessor` implements `Processor` interface.
=> :sparkles: Add command layer, add CommandWithMetadata interface

cmd/glaze/cmds/yaml.go, pkg/helpers/yaml/yaml.go, pkg/helpers/yaml/yaml_test.go
This pull request introduces a new flag, 'from-markdown', to the YamlCommand in the 'yaml.go' file. This flag allows the loading of YAMLs directly from code snippets in markdown files. 
Key changes include:
- Addition of the 'from-markdown' flag to the YamlCommand parameters in 'yaml.go'.
- Modification of the 'Run' function in 'yaml.go' to handle the 'from-markdown' flag.
- Modification of the 'Clean' function in 'yaml.go' and 'yaml_test.go' to handle the 'from-markdown' flag.
- Addition of a regular expression to remove trailing whitespaces in the 'Clean' function in 'yaml.go'.
- Modification of the 'getIndentLevel' function in 'yaml.go' to return a boolean indicating if a line is whitespace.
=> Added 'from-markdown' flag to load YAMLs from markdown code snippets

pkg/helpers/cast/cast.go, pkg/types/mod.go, prompto/glazed/create-command.yaml
This pull request introduces several new helper methods, enhances the documentation for row creation functions, and updates the `create-command.yaml` file. Here's a detailed breakdown of the changes:
1. **Helper Methods**: Two new helper methods, `GetAndCast` and `GetAndCastPtr`, have been added to `pkg/helpers/cast/cast.go`. These methods are designed to extract flags from the `ps` map in the command `Run()` methods. `GetAndCast` retrieves and casts a value from a map based on a provided key, returning a default value and an error message if the key is not found or the value cannot be cast to the desired type. `GetAndCastPtr` serves a similar function but is specifically used to fill optional pointer fields in structs.
2. **Documentation for Row Creation Functions**: The row creation …
=> Addition of Helper Methods and Documentation for Row Functions

pkg/cli/cobra.go
This pull request addresses a crash issue during the building of a Cobra command alias. The fix involves proper error handling and adjustments to the argument provision in the `BuildCobraCommandAlias` function.
=> Resolved Crash During Cobra Command Alias Building

pinocchio/glazed/create-help.yaml, pkg/doc/examples/skip-limit/01-skip-limit.md, pkg/middlewares/row/add-field.go, pkg/middlewares/row/fields-filter.go, pkg/middlewares/row/flatten-object.go, pkg/middlewares/row/lambda.go, pkg/middlewares/row/remove-duplicates.go, pkg/middlewares/row/remove-nulls.go, pkg/middlewares/row/rename-columns.go, pkg/middlewares/row/reorder-column.go, pkg/middlewares/row/replace.go, pkg/middlewares/row/skip-limit.go, pkg/middlewares/row/skip-limit_test.go, pkg/middlewares/row/sort-columns.go, pkg/middlewares/row/template.go, pkg/settings/flags/skip-limit.yaml, pkg/settings/glazed_layer.go, pkg/settings/settings_skip_limit.go
This pull request introduces the skip/limit pagination functionality to the Glazed application. The changes are spread across multiple files and can be summarized as follows:
- A new `SkipLimitMiddleware` has been added to the `row` package. This middleware is responsible for implementing the skip and limit functionality.
- Several existing files in the `middlewares/row` package have been updated to ensure they implement the `middlewares.RowMiddleware` interface.
- A new `SkipLimitParameterLayer` struct has been added, which includes methods for parsing skip and limit parameters from both command line flags and JSON.
- The `GlazedParameterLayers` struct in `glazed_layer.go` has been updated to include a `SkipLimitParameterLayer`.
- The `SetupTableProcessor` function in `glazed_layer.go` …
=> Implement skip/limit pagination functionality

pkg/doc/examples/skip-limit/01-skip-limit.md, pkg/settings/flags/skip-limit.yaml, pkg/settings/settings_skip_limit.go
This pull request addresses a naming conflict with the 'limit' and 'skip' flags in the Glazed pagination system. The changes include:
- Renaming the 'limit' and 'skip' flags to 'glazed-limit' and 'glazed-skip' respectively. This change is reflected across the documentation, YAML settings, and the Go settings file.
- Updating all instances in the documentation where the old flag names were used. This includes command examples and flag descriptions.
- Adjusting the flag names in the settings YAML file and the Go settings file to match the new names.
These changes are necessary to avoid conflicts with other programs (such as sqleton or pinocchio) that may use 'limit' and 'skip' as flag names. By prefixing our flags with 'glazed-', we ensure uniqueness and prevent potential clashes.
=> Resolving Flag Name Clash by Renaming 'limit' and 'skip' Flags

cmd/glaze/cmds/json.go, pkg/helpers/json/extract.go
This pull request introduces a new `--from-markdown` flag that enables JSON extraction directly from markdown formatted LLM responses. 
Key changes include:
- The `--from-markdown` flag is introduced to specify that the input is in markdown format.
- The `SanitizeJSONString` function is enhanced to handle markdown input. It now checks if the input is from markdown and sanitizes it accordingly.
- The `ExtractJSON` function is updated to use the enhanced `SanitizeJSONString` function.
This new feature will streamline the process of extracting JSON from markdown LLM responses, making it more efficient and user-friendly.
=> Add `--from-markdown` flag to extract JSON from markdown in `JsonCommand`

pkg/helpers/capture-output.go
This pull request introduces a new helper function for capturing standard output. 
Key changes:
- Addition of `CaptureOutput` function in the `helpers` package.
- The function executes a provided function and captures its standard output.
- Standard output capturing is handled in a separate goroutine to prevent deadlocks.
- Original stdout is restored after function execution.
- Errors during execution, capturing, or cleanup are returned along with the captured output.
=> Implementation of Standard Output Capture Helper

pkg/helpers/capture-output.go, pkg/helpers/files/temp-files.go, pkg/helpers/files/temp-files_test.go
This pull request introduces a new helper function and associated tests. The key changes include:
- Addition of a function to manage temporary files. This function deletes the oldest files in a directory based on a given mask, leaving only a specified number of the newest files. It returns a list of the paths of the deleted files. The function requires read and write permissions on the directory and will stop if it encounters a file it cannot delete, returning the files it has deleted so far along with the error.
- Inclusion of comprehensive tests for the new function. These tests cover a variety of scenarios, including valid inputs, no matching files, fewer files than specified, exactly the specified number of files, directories, zero files specified, negative file count, non-existent …
=> Introduction of Helper Function for Temporary File Management

cmd/glaze/cmds/markdown.go
This pull request addresses an issue with the output of code blocks in markdown files. 
Key changes:
- Added condition to check if the current node is a `FencedCodeBlock`.
- If true, the full content of the block is extracted and used as the node's text.
This change ensures the full content of code blocks is included in the output, improving markdown processing.
=> Fix Markdown Code Block Output

pkg/cmds/parameters/file.go
This pull request introduces a change that allows the use of "-" as an alias for stdin in file parameters.
Key changes include:
- When "-" is passed as a filename, the program now reads from stdin.
- A new FileData instance is created with the content read from stdin.
- The basename, path, relative path, and absolute path are all set to "stdin".
- The size is set to the length of the content read from stdin.
- The last modified time is set to the current time.
- The permissions are set to 0, and the isDirectory flag is set to false.
=> Implement stdin alias for file parameters

pkg/cli/cobra.go
- Introduces a new function to merge flag values parsed from both Viper and Cobra.
- Prioritizes flag values from Cobra when merging.
- Aims to centralize flag parsing logic and reduce redundancy.
- Ensures that command line flag overrides are respected.
=> Unify flag parsing using Viper and Cobra

pkg/cmds/parameters/parameters.go, pkg/helpers/maps/maps.go
- Refactored `StructToMap` function into `GlazedStructToMap` for clarity.
- Extracted struct pointer validation logic into `IsStructPointer` in `maps` package.
- Simplified `GlazedStructToMap` by utilizing `IsStructPointer` to check if the input is a pointer to a struct.
- Ensured `GlazedStructToMap` returns an empty map and no error when input is nil.
=> Refactor struct-to-map conversion and introduce IsStructPointer helper

pkg/cmds/parameters/cobra_test.go, pkg/cmds/parameters/parameters_test.go, pkg/cmds/parameters/parse.go, pkg/cmds/parameters/parse_test.go
This pull request updates the date parsing logic to use the local timezone
when no timezone is specified in the input. The changes ensure that date
inputs without explicit timezone information are interpreted relative to the
system's local timezone rather than defaulting to UTC.
Key changes include:
- Modification of date parsing in tests to expect local timezone results.
- Update of `ParseDate` function to use `dateparse.ParseLocal` instead of
`dateparse.ParseAny`, which defaults to local timezone.
- Adjustment of `TestSetValueFromDefaultDate` to parse the time in the local
timezone.
- Refactoring of test cases to use `time.Local` for expected results,
ensuring consistency with the new parsing behavior.
=> Parse date flags in local timezone by default

pkg/cmds/parameters/file.go
- Adds a `PrettyPrint` method to the `FileData` struct in `file.go`
- The `PrettyPrint` method formats the file data attributes into a readable
multi-line string
- Includes file attributes such as path, size, modification time, permissions,
and content (truncated)
- Utilizes `fmt.Sprintf` for formatting the string output
- Intended to improve debugging and logging of file data structures
Note: The pull request description provided was minimal. If there are specific
use cases or additional context that prompted this change, please provide them
to enhance the understanding of the motivation behind this addition.
=> Implement pretty print for FileData struct

pkg/cli/cobra.go
- Updated Cobra command execution to pass the command's context to
cancelable operations, allowing for graceful shutdowns and better
context management.
=> Pass command context to cancelable operations in Cobra CLI

pkg/cmds/layout/layout.go, pkg/cmds/loaders/loaders.go
This pull request introduces a significant refactor of the command loaders
interfaces within the `glazed` package. The changes aim to streamline the
loading process and reduce complexity by consolidating multiple loader
interfaces into a single, more generic one. Here are the key modifications:
- Consolidated `FSCommandLoader`, `ReaderCommandLoader`, and
`FileCommandLoader` into a single `CommandLoader` interface.
- Removed `ReaderCommandOrAliasLoader` and associated constructor function.
- Simplified `LoadCommandsFromFS` function to directly use the new
`CommandLoader` interface, removing the need for an intermediate
`FSFileCommandLoader` struct.
- Removed the `LoadCommandsFromReader` method from the interface, as loading
is now handled uniformly through the `LoadCommands` method.
- …
=> Refactor command loaders to simplify interfaces

pkg/cmds/layers/layer-impl.go, pkg/cmds/middlewares/cobra.go, pkg/cmds/middlewares/update.go, pkg/helpers/cast/cast.go, pkg/helpers/cast/map.go, pkg/settings/settings_template.go, pkg/settings/settings_template_test.go
- :ambulance: Only parse provided flags from viper when using middleware
- :ambulance: Only parse provided flags from cobra when using middleware
- :sparkles: Add middleware to parse from flag list manually
=> :ambulance: Don't use defaults from viper/cobra parsing layer

pkg/cli/cobra-parser.go, pkg/cli/cobra.go, pkg/cli/helpers.go, pkg/cmds/layers/layer.go, pkg/helpers/markdown/markdown.go
This pull request refactors the Cobra command setup to support layer
registration for non-glazed commands:
- Replaces `CobraParser`'s `Cmd` with `Layers` for parameter layer handling.
- Adds `NewCobraCommandFromCommandDescription` to create standalone `cobra.Command`.
- Introduces `NewCobraParserFromLayers` for `CobraParser` instantiation with layers.
- Implements `AddToCobraCommand` in `CobraParser` for adding layers to `cobra.Command`.
- Updates `BuildCobraCommandFromCommandAndFunc` to utilize new layer addition method.
- Enhances `ParameterLayers` with `AddToCobraCommand` for layer integration into `cobra.Command`.
- Refines comments to align with the updated layer-centric approach.
=> Enable non-glazed command layer registration in Cobra command creation

pkg/cmds/loaders/loaders.go
- Removes the constraint that enforces loading exactly one command per file
in the command loader logic.
- This change allows multiple commands to be defined and loaded from a single
file, enhancing flexibility in command organization.
- The removed lines previously threw an error if more than one command was
found, which is no longer the case after this update.
=> Remove single command restriction from command loader

pkg/cli/cli.go, pkg/cli/cobra-parser.go, pkg/cli/cobra.go, pkg/cmds/cmds.go, pkg/cmds/layers/cobra_flag_groups.go, pkg/cmds/layers/layer.go, pkg/cmds/parameters/cobra.go, pkg/help/cobra.go, pkg/help/help.go, pkg/help/render.go, pkg/help/templates/cobra-usage.tmpl
- :ambulance: Fix broken default flags display
- :pencil: Clean up overdue comment
- :sparkles: Display flag type when glazed parameter
- :sparkles: Implement --long-help
=> :sparkles: Add --long-help, flag types and fix default flags display

pkg/cmds/parameters/initialize-struct.go
=> :ambulance: Fix crash when creating wild card maps with enum key type

pkg/help/cobra.go, pkg/help/render.go, pkg/helpers/strings/strings.go
- :ambulance: List help that is not toplevel when asking for an explicit list
- :ambulance: Fix odd crash with glaze
=> :ambulance: Allow listing non toplevel help pages when listing explicitly

pkg/cmds/parameters/gather-parameters.go, pkg/helpers/cast/cast.go
- :ambulance: Fix parsing strings when reading from map
- :fire: Remove unnecessary and confusing string to int cast
=> :ambulance: Allow parsing of strings from the environment

cmd/glaze/cmds/markdown.go, pkg/cmds/parameters/initialize-struct.go, pkg/cmds/parameters/initialize-struct_test.go, pkg/doc/topics/19-writing-yaml-commands.md, pkg/helpers/files/files.go
This PR enhances JSON parsing capabilities and adds a temporary file helper:
- Improve JSON parsing when initializing structs:
• Better handling of map[interface{}]interface{} types
• Recursive sanitization of maps and slices for JSON compatibility
• Enhanced error handling and reporting for JSON unmarshaling
- Add FileData handling:
• Support for initializing struct fields from FileData
• Handle string, []byte, and parsed content from FileData
- Implement CreateTemporaryFile helper function:
• Creates temporary files with custom prefix and name
• Ensures temporary directory exists
- Expand test coverage:
• New tests for JSON parsing from various sources (structs, maps)
• Tests for FileData handling and edge cases
• Tests for handling map[interface{}]interface{} types
- Add comprehensive …
=> Improve JSON parsing for struct initialization and add temporary file helper

pkg/cmds/parameters/parameters.go, pkg/formatters/yaml/yaml.go
- Convert *time.Time to time.Time before YAML encoding
- Remove nil time.Time values from the map to prevent encoding errors
=> Fix YAML encoding crash for time.Time pointers

changelog.md, pkg/cli/cobra-parser.go, pkg/doc/topics/03-templates.md, pkg/helpers/templating/templating.go
Adds two major features:
Random template functions:
- randomChoice - pick random element from list
- randomSubset - get n random elements
- randomPermute - random list permutation 
- randomInt/Float - generate random numbers
- randomString/StringList - generate random strings
- randomBool - random boolean
Optional glazed command layer:
- New WithSkipGlazedCommandLayer option
- Allows skipping the default glazed command layer
- Useful when building custom CLIs without glazed features
Documentation:
- Added examples and descriptions for all new template functions
- Improved formatting and clarity of template docs
- Updated string/number function documentation
=> Add random template functions and optional glazed command layer

pkg/cmds/parameters/gather-parameters.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parameters_test.go, pkg/cmds/parameters/test-data/gather-parameters.yaml
Improves parameter type casting and validation by:
- Modifies CheckValueValidity to return properly cast values along with validation
- Adds setReflectValue method to handle type-safe value setting
- Simplifies choice validation logic
- Adds proper type casting for all parameter types (string, int, float, bool, etc)
- Improves handling of key-value maps and lists
- Adds test coverage for all parameter types and casting scenarios
Key changes:
- CheckValueValidity now returns (interface{}, error) instead of just error
- Values are cast to their proper target types during validation
- Reflection-based value setting is type-safe and properly handled
- Better error messages when type casting fails
=> Improve type casting and validation in parameter handling

changelog.md, pkg/cli/cli.go, pkg/cli/cobra-parser.go, pkg/cli/cobra.go, pkg/cmds/json-schema.go
Major refactoring of command settings layers and addition of JSON schema support:
Command Settings Changes:
- Split monolithic GlazedCommandLayer into separate focused layers:
- CommandSettingsLayer: Core command options (yaml/parameters/schema output)
- ProfileSettingsLayer: Profile loading options 
- CreateCommandSettingsLayer: Command creation options
- Layers are now opt-in via WithProfileSettingsLayer() and WithCreateCommandSettingsLayer()
- CommandSettingsLayer remains default but can be disabled with WithSkipCommandSettingsLayer()
JSON Schema Support:
- Add ToJsonSchema() method to generate JSON Schema for commands
- Add --print-schema flag to output command schema
Breaking Changes:
- GlazedCommandSettings struct split into separate settings structs
- GlazedCommandLayer renamed to …
=> Split command settings layers and add JSON schema support

pkg/cmds/cmds.go, pkg/cmds/loaders/multi-loader.go, pkg/cmds/runner/run.go, pkg/doc/topics/15-using-commands.md, pkg/doc/topics/20-using-multi-loader.md, pkg/doc/topics/21-cmds-middlewares.md
Adds several helpers to support building MCP tools with glazed commands:
- New MultiLoader for type-based command loading:
- Dispatches to registered loaders based on command type field
- Fallback to default loader for untyped commands
- Automatic loader detection based on file content
- New runner package for programmatic command execution:
- ParseAndRun helper for simple command execution
- Configurable parameter parsing with options
- Support for environment variables, Viper config, and custom middlewares
- Separate parse and run steps for advanced control
- Additional documentation:
- Tutorial for using MultiLoader
- Guide for running commands programmatically
- Expanded middleware documentation with examples
- Other changes:
- Added Type field to CommandDescription
- Changed command …
=> Add command running and loading helpers for MCP tools

go.mod, go.sum, pkg/cmds/helpers/test-helpers.go, pkg/cmds/layers/layer.go, pkg/cmds/layers/parsed-layer.go, pkg/cmds/layers/parsed-layer_test.go, pkg/cmds/middlewares/cobra.go, pkg/cmds/middlewares/layers.go, pkg/cmds/middlewares/tests/multi-update-from-map.yaml, pkg/cmds/middlewares/update.go, pkg/cmds/parameters/cobra.go, pkg/cmds/parameters/gather-arguments.go, pkg/cmds/parameters/gather-parameters.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parse.go, pkg/cmds/parameters/parse_test.go, pkg/cmds/parameters/parsed-parameter.go, pkg/cmds/parameters/strings.go, pkg/cmds/parameters/strings_test.go, pkg/cmds/parameters/viper.go, pkg/helpers/reflect/reflect.go, pkg/helpers/reflect/reflect_test.go, pkg/lua/lua.go, pkg/settings/glazed_layer.go, pkg/settings/settings_fields-filters.go
This PR improves type safety and error handling around parameter value parsing and 
validation:
Key Changes:
- Add strict type checking when updating parameter values to ensure values match
declared parameter types
- Propagate errors through parameter update/merge operations instead of silently
failing
- Make map[string]string the concrete type for key-value parameters instead of
map[string]interface{}
- Add helper functions to safely handle interface{} type stripping and validation
- Clean up redundant code in glazed layer implementations using loops over layer
slices
- Add extensive tests for interface stripping and type conversion edge cases
Type Checking:
- Parameter values are now validated against their declared type before being set
- Invalid type conversions result in errors …
=> Enforce stricter type checking and improve error handling for parameter values

pkg/cmds/helpers/test-helpers.go, pkg/cmds/parameters/gather-arguments_test.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parameters_from_defaults_test.go, pkg/cmds/parameters/parse.go, pkg/cmds/parameters/parse_test.go, pkg/cmds/parameters/parsed-parameter.go, pkg/helpers/cast/normalize.go, pkg/helpers/reflect/reflect.go, pkg/helpers/reflect/reflect_test.go
Fixes issues with type handling when dealing with nested interface{} and pointer 
types by:
* Modify StripInterface to preserve pointer types while stripping interface wrappers
* Add NormalizeValue function to handle type comparison and normalization
* Fix parameter validation to properly handle object lists
Key changes:
* StripInterface now returns *T instead of T for pointer types
* Object lists are properly typed as []map[string]interface{} 
* Added value normalization for consistent comparisons
* Better handling of nil values and defaults
The changes ensure proper type preservation when dealing with interface{} wrapped
pointer types, fixing several edge cases around parameter handling and validation.
=> Fix type preservation for nested interface pointers

pkg/cli/cobra-parser.go, pkg/cli/cobra.go, pkg/cmds/loaders/loaders.go, pkg/cmds/parameters/cobra.go, pkg/codegen/glazed.go, pkg/doc/topics/20-using-multi-loader.md
This PR adds functionality to validate command files by type before attempting 
to load them:
* Add `CheckYamlFileType` helper to verify YAML file type field
* Improve error messages for flag conflicts by including flag usage
* Fix code generation for default parameter values using `InterfaceAddr`
* Add more detailed error logging for command loading failures
* Update documentation examples to use "sqleton" instead of "sql" type
These changes improve error handling and diagnostics when loading commands, 
making it easier to identify issues with command files and flag conflicts.
=> Add helper to check for file validity when loading commands

Makefile, pkg/doc/examples/regex-filters/regex-filters.md, pkg/middlewares/row/add-field_test.go, pkg/middlewares/row/fields-filter.go, pkg/middlewares/row/fields-filter_test.go, pkg/settings/flags/fields-filters.yaml, pkg/settings/settings_fields-filters.go
This PR adds regex-based filtering capabilities to the fields filter 
middleware.
- Add regex pattern support for field inclusion and exclusion
- Refactor `FieldsFilterMiddleware` to use functional options pattern
- Add new command line flags: `--regex-fields` and `--regex-filters`
- Improve field filtering logic to handle combinations of filters
- Add comprehensive tests for regex filtering
Users can now filter fields using regex patterns:
```
--regex-fields "^test[0-9]+$"
--regex-filters "^temp_.*$"
--fields id,name --regex-fields "^meta_.*$" --filter timestamp
```
The precedence rules ensure predictable behavior when combining different filter
types.
=> Add regex filters for field filtering

pkg/cmds/parameters/parse.go, pkg/helpers/maps/maps.go
This PR adds two main features:
* Support for `.jsonl` file extension in object list parameters (in addition to
existing `.ndjson` support)
* New map helper functions for safely accessing nested values:
* `Get[T]()` - Generic accessor for retrieving typed values from nested maps
* `GetString()` - Convenience function for string values
* `GetInteger[T]()` - Accessor for integer values with type conversion support
=> Add JSONL support and map helper functions

pkg/cmds/logging/init.go, pkg/cmds/logging/layer.go
This PR adds a new `--log-to-stdout` flag that enables logging to both a file and 
stdout simultaneously when a log file is specified.
=> Add --log-to-stdout flag for simultaneous file and stdout logging

cmd/examples/parameter-types/README.md, cmd/examples/parameter-types/config.yaml, cmd/examples/parameter-types/main.go, cmd/examples/parameter-types/sample-lines.txt, cmd/examples/parameter-types/sample-list.json, cmd/examples/parameter-types/sample-text.txt, cmd/examples/parameter-types/sample.json, cmd/examples/parameter-types/sample.yaml, cmd/examples/parameter-types/simple-config.yaml, pkg/cmds/json-schema.go, pkg/cmds/parameters/cobra.go, pkg/cmds/parameters/parameter-type.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parse.go, pkg/cmds/parameters/render.go, pkg/cmds/parameters/viper.go, pkg/codegen/glazed.go, pkg/doc/topics/15-using-commands.md, pkg/doc/topics/16-adding-parameter-types.md, pkg/lua/lua.go
- Add `ParameterTypeSecret` constant for sensitive string values
- Behaves like string parameters but masks values when displayed
- Integrates with all existing parameter processing systems
- Secret values display as `***` for strings ≤6 characters
- Longer strings show first 2 chars + `***` + last 2 chars
- Actual values remain unchanged in memory for processing
- Update Cobra command flag handling for secret parameters
- Add Viper configuration support for secret values
- Include in JSON schema generation as string type
- Support in Lua parameter parsing
- Add to code generation utilities
- Create comprehensive parameter types example demonstrating all available
types including the new secret type
- Include sample files and documentation for testing different parameter
scenarios
=> Add secret parameter type with masked display

AGENT.md, pkg/cmds/logging/init.go, pkg/cmds/logging/layer.go, pkg/cmds/middlewares/cobra.go
• **Case-insensitive log level parsing**: Log level validation now accepts both
uppercase and lowercase values (e.g., "DEBUG" and "debug")
Both `--log-level=debug` and `--log-level=DEBUG` now work identically.
=> Allow uppercase and lowercase log levels

pkg/help/cmd/cobra.go, pkg/help/cmd/templates/cobra-usage.tmpl
- Add missing cobra command fields to template data context
- Fix template nil pointer error when checking aliases
This ensures the help system can properly render cobra command help pages
without template execution errors.
=> Fix cobra command help template rendering

.gitignore, pkg/cli/cobra.go, ttmp/2025-08-05/01-research-the-context-cancellation-bug-in-glazed.md, ttmp/2025-08-05/02-signal-cancellation-test-results.md, ttmp/2025-08-05/signal-test/main.go
• **Extended signal handling to GlazeCommands**: Previously only classic 
commands had signal handling via `signal.NotifyContext()`
• **Added SIGTERM support**: Both command types now handle SIGINT and SIGTERM 
signals for proper graceful shutdown
• **Consistent context propagation**: All commands now use signal-aware 
context for operations and processor closing
=> Add signal handling for GlazeCommands with SIGTERM support

pkg/cmds/logging/init.go, pkg/doc/tutorials/build-first-command.md
- Modify logging behavior to disable color output when not in an 
interactive terminal (tty).
- Update documentation to guide users on initializing logging with 
Cobra commands and Viper configuration.
=> Do not use color in logging for non-interactive ttys

pkg/cmds/cmds.go, pkg/cmds/layers/parsed-layer.go, pkg/cmds/middlewares/cobra.go, pkg/cmds/parameters/viper.go, pkg/doc/topics/13-layers-and-parsed-layers.md, pkg/doc/topics/layers-guide.md
- Introduce support for registering layers under explicit slugs using
`cmds.WithLayersMap`.
- Enable multiple instances of the same layer with different slugs for
improved parsing and debugging.
- Ensure that if a layer's internal slug differs from the provided key,
the layer can be cloned and aligned to maintain consistency.
- Enhance metadata associated with layers during parsing for better
traceability.
- Update documentation to provide examples on how to use the new feature
effectively.
=> Allow multiple instances of the same layer with different slugs
