go-go-golems/glazed

cmd/glaze/doc/topics/markdown-style.md, pkg/help/cobra.go, pkg/help/help.go, pkg/help/render.go
Some quality of life improvements! This was fun to pair on.
=> :lipstick: :memo: Improve markdown styling and add docs

pkg/middlewares/table.go
=> Fix preserver order middleware helper

go.mod, pkg/cli/cobra.go
=> :ambulance: Fix special handling of filter when fields is specified

pkg/formatters/table.go
=> :lipstick: Output arrays as comma separated strings in table mode

pkg/cmds/cmds.go, pkg/cmds/doc.go
This adds a LoadCommandsFromFS loader that makes it possible to 
load commands from more than just YAML files
=> Add LoadCommandsFromFS

doc/logs/2022-12-04.md, pkg/cli/settings_template.go, pkg/cli/settings_template_test.go
Closes #141
- ;art: Add unit tests to catch bug
- :ambulance: Fix template-field parsing
=> :ambulance: Fix template-field flag parsing

.golangci.yml, pkg/cmds/cobra.go, pkg/cmds/parameters.go, pkg/cmds/parameters_test.go, pkg/helpers/reflect_test.go, pkg/helpers/templating.go
Closes #143
- :sparkle: Add string-list-from-file type
- :art: Update golangci
=> Add stringListFromFile

pkg/formatters/csv.go, pkg/formatters/csv_test.go, pkg/formatters/json.go, pkg/formatters/json_test.go, pkg/formatters/table.go, pkg/formatters/table_test.go, pkg/formatters/template.go, pkg/formatters/template_test.go, pkg/formatters/yaml.go, pkg/formatters/yaml_test.go, pkg/helpers/csv.go, pkg/types/mod.go
This really warrants a much bigger pass, see #146
=> :ambulance: Fix rename middleware leading to empty output

cmd/glaze/cmds/json.go, cmd/glaze/cmds/yaml.go, pkg/cli/cobra.go, pkg/cmds/alias.go, pkg/cmds/cmds.go
This paves the way for some async step composition of commands in the future
Closes #158
=> :art: Use context as first argument of Run

pkg/cli/settings_fields-filters.go
=> :ambulance: Fix fields-filter not reordering columns

pkg/cli/cobra.go, pkg/helpers/strings.go
Closes #169
Closes #171
- :sparkles: Add --create-command
- :sparkles: Fix create-alias to work with slices
=> Add create-command, fix create-alias

pkg/cli/cobra.go, pkg/cmds/cmds.go
=> :sparkles: Add ExitWithoutGlaze error

Makefile, pkg/cmds/layers/groups.go
- :arrow_up: Bump makefile for 0.2.18
- :art: Little tweaks to finish up #173 and also #136
=> Polish up #173 and #167

pkg/cli/cobra.go
Closes https://github.com/go-go-golems/sqleton/issues/107
=> :art: :pencil: Tiny additional information that has a big effect when initializing commands

cmd/glaze/cmds/csv.go, cmd/glaze/main.go, pkg/helpers/csv.go
=> :sparkles: Add CSV input

cmd/glaze/cmds/csv.go, cmd/glaze/cmds/json.go, cmd/glaze/cmds/yaml.go, pkg/cli/glazed_layer.go, pkg/cmds/alias.go, pkg/cmds/cmds.go, pkg/cmds/processor.go, pkg/types/mod.go
- :sparkles: Make GlazeProcessor an interface
- :art: Add finalized flag to table to avoid finalizing multiple times
- :sparkles: Spruce up layer options handling
=> Refactor GlazeProcessor and add more Layer options

pkg/cli/flags/select.yaml, pkg/cli/glazed_layer.go, pkg/cli/settings_select.go, pkg/formatters/simple.go
=> :sparkles: Add select output formatter

pkg/cmds/processor.go, pkg/middlewares/jq.go, pkg/middlewares/jq_test.go, pkg/middlewares/mod.go, pkg/middlewares/object.go
=> :sparkles: Add multi-object support for the object middleware

pkg/cli/cobra.go
=> :ambulance: :lipstick: :mute: Don't printout context canceled errors

pkg/cli/flags/fields-filters.yaml, pkg/cli/settings_fields-filters.go, pkg/middlewares/table.go
=> :sparkles: Add feature to filter out null

pkg/cli/glazed_layer.go, pkg/cmds/layers/cobra_flag_groups.go, pkg/cmds/layers/groups.go, pkg/cmds/layers/groups_test.go
=> :ambulance: Fix missing prefix handling of flag group usage

pkg/cli/cobra.go, pkg/cli/settings_rename.go, pkg/cmds/cmds.go, pkg/cmds/layers/groups.go, pkg/cmds/parameters/cobra.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/parse.go
- :ambulance: Better error handling
- :art: Refactor to allow to load parameters from a map
=> Cleanup for facture shenanigans

pkg/cmds/parameters/cobra.go, pkg/cmds/parameters/parameters.go, pkg/cmds/parameters/render.go, pkg/cmds/parameters/render_test.go, pkg/helpers/cast/cast.go, pkg/helpers/templating/templating.go
- :art: :umbrella: Add some RenderValue unit tests
- :ambulance: Fix render of Date
- :ambulance: Fix render of Object and ObjectList preliminarily
=> Fix RenderValue of Date

pkg/cli/cliopatra/program.go
Related to go-go-golems/cliopatra#9
=> :sparkles: Add cliopatra program watcher

cmd/glaze/doc/examples/replace/replace-add-fields.md, pkg/cli/flags/replace.yaml, pkg/cli/settings_replace.go, pkg/middlewares/table/add-field.go, pkg/middlewares/table/add-field_test.go
Closes #258
- :sparkles: Add --add-fields functionality
- :bulb: Add documentation
=> Add constant fields

cmd/glaze/doc/examples/jq/01-jq-replace.md, cmd/glaze/doc/examples/jq/02-jq-filter.md, pkg/cmds/processor.go
- :ambulance: Fix jq middleware
- :bulb: Add a few --jq examples
=> :ambulance: Fix jq middleware for proper filtering

pkg/formatters/simple/simple.go
=> :ambulance: Remove trailing separator when using --select

cmd/glaze/cmds/csv.go, pkg/formatters/csv/csv_test.go, pkg/helpers/csv/csv.go
=> :ambulance: Fix csv command not preserving column order

cmd/glaze/doc/topics/05-table-format.md, pkg/cli/flags/output.yaml, pkg/cli/settings_output.go, pkg/formatters/table/style.go, pkg/formatters/table/style_test.go, pkg/formatters/table/table.go
Closes #275
- :sparkles: Add style representation for YAML marshalling
- :sparkles: Add support for saving and loading style files from YAML
- :books: Add documentation
=> :sparkles: Add support for pretty style loading from YAML

cmd/glaze/cmds/docs.go, cmd/glaze/cmds/html/cmds.go, cmd/glaze/cmds/markdown.go, pkg/cli/cobra.go, pkg/cli/glazed_layer.go, pkg/cli/settings_output.go, pkg/cmds/cmds.go, pkg/cmds/layout/layout.go, pkg/cmds/parameters/parse.go, pkg/cmds/processor.go, pkg/helpers/templating/templating.go
- :sparkles: Update GlazeProcessor SetupProcessor return values
- :ambulance: :art: Use s.Template instead of trying to access the raw parameter which could be nil and not a string
- :sparkles: :lipstick: Add layouts to sqleton and glazed command
- :sparkles: Add layouts to glazed
- :art: Add toDate to templating helpers
- :art: Handle on/off for boolean values
=> Add layout to commands, misc fixes and features

pkg/formatters/json/json.go, pkg/formatters/table/table.go, pkg/helpers/templating/templating.go
- :art: Filter out templates that don't match the baseDir
- :art: Add WithTable option for json formatter to do table embedded JS output in parka
=> :ambulance: Fix random layout order, small improvements

cmd/glaze/cmds/json.go, pkg/cli/cobra.go
- :art: Add clarification to input-is-array flag
- :art: Clean up AddCommandsToRootCommand signature
=> Cleanup AddCommandsToRootCommand

pkg/formatters/table/table.go
Add newline after the human table output for cosmetics
=> :lipstick: Add newline after output table

cmd/glaze/cmds/docs.go, cmd/glaze/cmds/html/cmds.go, cmd/glaze/cmds/markdown.go, doc/vhs/demo.sh, go.mod, go.sum, pkg/cli/cobra.go, pkg/formatters/csv/csv.go, pkg/formatters/csv/csv_test.go, pkg/formatters/excel/excel.go, pkg/formatters/formatter.go, pkg/settings/glazed_layer.go, pkg/settings/settings_output.go
- :fire: Remove deprecated files
- :ambulance: Fix CSV writer to file
- :sparkles: Add row outputs for CSV and co
- :sparkles: Add row outputs for CSV and co
- :sparkles: Make excel a RowOutput
- :pencil: Whitespace
- :arrow_up: Bump go.sum
=> Add more row output formatting

cmd/glaze/doc/examples/output/sql-output.md, pkg/formatters/sql/sql.go, pkg/formatters/sql/sql_test.go, pkg/settings/flags/output.yaml, pkg/settings/settings_output.go
Closes #327 
- :sparkles: Add sql output formatter
- :sparkles: Add SQL output options
- :bulb: Add documentation for the sql output flags
=> :sparkles: Add SQL output

pkg/cli/cobra.go, pkg/formatters/json/json.go, pkg/formatters/table/table.go
=> :ambulance: Don't forget the inter row comma when outputting as json without output-as-objects

pkg/helpers/capture-output.go
Cleanup LLM documentation uselessness.
=> Refactoring and Simplification of CaptureOutput Function

pkg/cmds/cmds.go, pkg/cmds/loaders/loaders.go, pkg/help/cobra.go, pkg/middlewares/row/fields-filter.go
Small cosmetic improvements for the new ls-commands
=> Small cosmetic improvements for ls-commands

pkg/cmds/parameters/parse.go, pkg/cmds/parameters/parse_test.go
Enhancements in this pull request:
- Introduced support for loading object lists from NDJSON files.
=> Add NDJSON parsing support for object lists

pkg/cli/cli.go, pkg/cli/cobra-parser.go, pkg/cmds/layers/parsed-layer.go, pkg/cmds/middlewares/profiles.go
Currently only in geppetto, where we will refine the usability. Then
we will move it to the other go go programs as well.
=> :sparkles: Add profiles support

pkg/cli/cobra-parser.go, pkg/doc/doc.go, pkg/help/help.go, pkg/settings/flags/fields-filters.yaml, pkg/settings/settings_fields-filters.go
- :art: Make short help layers option append
- :art: Add the reorder-columns flag
- :ambulance: Import all docs recursively
- :art: Allow HelpSystem.Section to be marshalled to yaml
=> :sparkles: Add reorder-columns flag

cmd/glaze/cmds/markdown.go, pkg/cli/cliopatra/program.go, pkg/cli/cobra-parser.go, pkg/cli/helpers.go, pkg/cmds/cmds.go, pkg/cmds/helpers/test-helpers.go, pkg/cmds/loaders/loaders.go, pkg/cmds/parameters/gather-arguments.go, pkg/cmds/parameters/initialize-struct.go, pkg/cmds/parameters/parse_test.go, pkg/cmds/parameters/strings.go, pkg/formatters/json/json.go, pkg/formatters/simple/simple.go, pkg/formatters/sql/sql.go, pkg/formatters/table/style.go, pkg/formatters/table/table.go, pkg/formatters/template/template.go, pkg/formatters/yaml/yaml.go, pkg/help/help.go, pkg/helpers/cast/map.go, pkg/helpers/reflect/reflect.go, pkg/middlewares/row/rename-columns.go
- :art: Correctly format file: sources
- :art: Add FullPath() option to CommandDescription
- :sparkles: Add edit-command verb
- :art: Use github errors instead of fmt.Errorf
=> :art: Add FullPath() helper to allow editing of file commands

cmd/glaze/cmds/json.go, pinocchio/glazed/create-help.yaml, pinocchio/glazed/create-template-command.yaml, pkg/cli/cobra-parser.go, pkg/formatters/yaml/yaml.go, pkg/settings/settings_output.go, prompto/glazed/create-command.yaml
This pull request introduces two main features and several improvements:
- **Tail Mode**: 
- Added a new `tail` parameter to the JSON command.
- **YAML Row Formatter**:
- Enables streaming individual rows in YAML format.
=> add tail mode and yaml row formatter

pkg/cmds/parameters/parameters.go
- Update error messages in parameter validation
=> Improve error message for key value map parameter validation

pkg/cmds/loaders/loaders.go, pkg/doc/topics/00-documentation-guidelines.md
Adds detailed documentation guidelines for Go-Go-Golems projects covering:
- Document structure and frontmatter requirements
- Writing style and tone guidelines
- Code example best practices
- Content organization patterns
- Package reference standards
- Configuration examples and templates
=> Add comprehensive documentation guidelines

.github/workflows/lint.yml, .github/workflows/push.yml, pkg/cmds/cmds.go, pkg/config/cobra-config-command.go, pkg/config/editor.go, pkg/doc/topics/15-using-commands.md
Adds two major features:
Command Tagging and Metadata:
- New `Tags` field for categorizing commands
- New `Metadata` field for arbitrary command attributes
- Helper functions `WithTags()` and `WithMetadata()` for setting these fields
Configuration Management:
- New `config` command with subcommands:
- list: Show all config keys/values
- get/set: Read and write individual values
- delete: Remove a config key
- edit: Open config file in default editor
- show: Display full config contents
- path: Show config file location
- Supports YAML configuration files
- Uses standard config directories
- Handles missing config files gracefully
=> Add configuration management and command tagging support

pkg/cmds/middlewares/middlewares.go, pkg/cmds/parameters/parameters.go
* Fix missing `IsArgument` field in parameter definition cloning
* Add proper logging initialization in the main command
=> Fix missing arguments and improve parameter handling

pkg/doc/topics/15-using-commands.md, pkg/doc/topics/22-cmd-loaders.md, pkg/doc/topics/22-templating-helpers.md
- Updates and expands the events and PubSub documentation with practical examples
- Adds new documentation for the conversation package covering message types and tree
management
- Adds detailed guides for the embeddings package with examples for different
providers and caching strategies
- Adds comprehensive tutorial for the steps abstraction, covering AI inference,
tool calling, and composition patterns
Also includes a small fix to the EventRouter to use NopLogger by default instead of
the standard logger, reducing log noise when verbose mode is not enabled.
=> Add comprehensive documentation for core Geppetto packages

pkg/cmds/middlewares/custom-config.go, pkg/cmds/middlewares/custom-config_test.go, pkg/cmds/middlewares/custom-profiles_test.go, pkg/cmds/middlewares/profiles.go, pkg/doc/topics/12-profiles-use-code.md, pkg/doc/topics/21-cmds-middlewares.md
This PR adds new middleware capabilities for loading configuration from custom
sources, enabling more flexible configuration management across applications.
• **GatherFlagsFromCustomViper**: Load config from specific files or other 
app's default locations
• Supports explicit config file paths via `WithConfigFile()`
• Supports loading from other app configs via `WithAppName()`
• Temporarily replaces global viper instance during processing
• Includes comprehensive test coverage
• **GatherFlagsFromCustomProfiles**: Load profiles from custom sources
• Supports explicit profile file paths via `WithProfileFile()`
• Supports loading from other app profiles via `WithProfileAppName()`
• Optional profile validation with `WithProfileRequired()`
• Graceful handling of missing files/profiles when not …
=> Add custom configuration and profile middleware for flexible config loading

pkg/cmds/parameters/initialize-struct.go
• **Direct FileData assignment**: Added support for destinations that expect
FileData types directly, including both value and pointer variants
• **Enhanced slice parsing**: Improved handling of non-byte slices by
attempting to deserialize ParsedContent into the target slice type
• **JSON fallback mechanism**: Implemented JSON marshaling/unmarshaling as a
fallback when direct assignment fails for complex types
• **Better error handling**: More specific error messages for unsupported
slice types
=> Fix parsing of file data to handle custom structs

README.md, doc/cmd-layers-guide.md, doc/cmd-middlewares-guide.md
Adding some ampcode generated documentation that helped at least me understand how the layers and middlewares parts of glazed work and the capabilities they expose.
Side note: It feels like these might actually belong in a different package as they feel somewhat different from the core described problem domain of glazed in terms of parsing & exposing structured data, but maybe not, or maybe glazed has just evolved to meet a broader set of needs.
=> Document cmd layers and middlewares

cmd/examples/help-system/README.md, cmd/examples/help-system/docs/configuration-topic.md, cmd/examples/help-system/docs/data-pipeline-application.md, cmd/examples/help-system/docs/database-tutorial.md, cmd/examples/help-system/docs/json-example.md, cmd/examples/help-system/main.go, pkg/doc/topics/01-help-system.md
This PR completely rewrites the help system documentation to provide a 
comprehensive guide for developers implementing CLI help systems with Glazed.
• **Complete rewrite** of main help system documentation
- Expanded from basic overview to comprehensive API guide
- Added detailed programmatic usage examples
- Documented query DSL syntax and boolean logic
- Included section metadata and filtering capabilities
• **New structure** focuses on practical implementation
- Section types and structure explanation
- Programmatic usage patterns with code examples
- Query system with DSL syntax documentation
- Cobra integration patterns
- Metadata filtering and dynamic discovery
• **Query DSL capabilities**
- Type-based queries (`type:example`)
- Boolean operations (`AND`, `OR`, `NOT`)
- Metadata …
=> Overhaul help system documentation with comprehensive examples and API guide
